 
language: c
dist: xenial

# Install dependencies
install:
 - sudo apt-get update
 - sudo apt-get install -y -t xenial-backports meson
 - sudo apt-get install libgtk-3-dev libjson-glib-dev libsoup2.4-dev valac

script:
  - meson build
  - ninja -C build
